### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by IgorChebotenko** [IgorChebotenko/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, інші), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by MihalichLuda2020** [comment]
"The one minute. The soldier’s minute. In a battle, that’s all you get. One minute of everything at once. And anything before is nothing. Everything after, nothing. Nothing in comparison to that one minute."

is the leader of the Birmingham criminal gang, the Peaky Blinders and the patriarch of the Shelby Family.
