### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by IgorChebotenko** [IgorChebotenko/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by MihalichLuda2020** [comment]
LANGUAGES
English
French
Gypsy
SKILLS
Forward looking, Competent, Inspire people, Stress resistant, Fearless.

CHARACTER
Integrity, Courage, Accountability, Temperance.

LIKES
My Wife, My Son, Family, Weapons, Whiskey, Horses, Cars, Women, Cigarettes, Golf, Money.

WANTS
I want to develop my business.

MILITARY SERVICE
SERVICE
British Army
YEARS OF SERVICE
1914-1918
UNIT
179th Tunnelling Company
BATTLES
Mons, The Somme, Verdun
